"""empty message

Revision ID: 0dca48ad9cce
Revises: 9b0207649e16
Create Date: 2020-07-18 01:58:54.313467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dca48ad9cce'
down_revision = '9b0207649e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'about')
    # ### end Alembic commands ###
