"""empty message

Revision ID: 0e663d7ad35b
Revises: 6a8d9c7f9aab
Create Date: 2020-07-11 22:29:06.544128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e663d7ad35b'
down_revision = '6a8d9c7f9aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('item_metadata', 'field_edited')
    op.add_column('items', sa.Column('season', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'season')
    op.add_column('item_metadata', sa.Column('field_edited', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
