"""empty message

Revision ID: 21a1282a5a7d
Revises: 72dac8c3b4bd
Create Date: 2020-08-30 16:34:02.126230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21a1282a5a7d'
down_revision = '72dac8c3b4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('season_collection', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('elasticsearch')
    op.drop_table('temp_style_registrations')
    op.add_column('comments', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'collections', ['collection_id'], ['id'])
    op.add_column('looks', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'looks', 'collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'looks', type_='foreignkey')
    op.drop_column('looks', 'collection_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'collection_id')
    op.create_table('temp_style_registrations',
    sa.Column('style_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('elasticsearch',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_released', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('form_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('brand_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('season', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metadata_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('colors', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('styles', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('materials', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subcategory_name', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_table('collections')
    # ### end Alembic commands ###
