"""empty message

Revision ID: 32b6fdd8d008
Revises: 0e663d7ad35b
Create Date: 2020-07-17 22:53:15.599404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b6fdd8d008'
down_revision = '0e663d7ad35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'color_registrations', 'items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'color_registrations', 'colors', ['color_id'], ['id'])
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('idx_16423_ix_users_email', table_name='users')
    op.drop_index('idx_16423_ix_users_username', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_16423_ix_users_username', 'users', ['username'], unique=True)
    op.create_index('idx_16423_ix_users_email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(None, 'color_registrations', type_='foreignkey')
    op.drop_constraint(None, 'color_registrations', type_='foreignkey')
    # ### end Alembic commands ###
