"""empty message

Revision ID: 45052bf142c5
Revises: 2695716d0e61
Create Date: 2020-09-12 19:59:49.207793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45052bf142c5'
down_revision = '2695716d0e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('looks_subcategory_id_fkey', 'looks', type_='foreignkey')
    op.drop_constraint('looks_category_id_fkey', 'looks', type_='foreignkey')
    op.drop_column('looks', 'form_date')
    op.drop_column('looks', 'category_id')
    op.drop_column('looks', 'subcategory_id')
    op.drop_column('looks', 'season')
    op.add_column('style_registrations', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.add_column('style_registrations', sa.Column('look_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'style_registrations', 'looks', ['look_id'], ['id'])
    op.create_foreign_key(None, 'style_registrations', 'collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'style_registrations', type_='foreignkey')
    op.drop_constraint(None, 'style_registrations', type_='foreignkey')
    op.drop_column('style_registrations', 'look_id')
    op.drop_column('style_registrations', 'collection_id')
    op.add_column('looks', sa.Column('season', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('looks', sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('looks', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('looks', sa.Column('form_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('looks_category_id_fkey', 'looks', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('looks_subcategory_id_fkey', 'looks', 'subcategories', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###
