"""empty message

Revision ID: 53609d2595a8
Revises: 4dad688de007
Create Date: 2020-06-29 21:15:55.471407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53609d2595a8'
down_revision = '4dad688de007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('item_metadata', 'field_edited')
    op.add_column('items', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'gender')
    op.add_column('item_metadata', sa.Column('field_edited', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
