"""empty message

Revision ID: 56dea904792b
Revises: d8fd899d2ee0
Create Date: 2020-09-13 10:09:31.367834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56dea904792b'
down_revision = 'd8fd899d2ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thumbnails', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'thumbnails', 'collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thumbnails', type_='foreignkey')
    op.drop_column('thumbnails', 'collection_id')
    # ### end Alembic commands ###
