"""empty message

Revision ID: 6a8d9c7f9aab
Revises: bcfae80cc16f
Create Date: 2020-07-11 22:13:25.766943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a8d9c7f9aab'
down_revision = 'bcfae80cc16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('item_metadata', 'field_edited')
    op.add_column('items', sa.Column('fit', sa.String(), nullable=True))
    op.add_column('items', sa.Column('form_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'form_date')
    op.drop_column('items', 'fit')
    op.add_column('item_metadata', sa.Column('field_edited', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
