"""empty message

Revision ID: 72dac8c3b4bd
Revises: e2ac40f266b2
Create Date: 2020-08-13 20:26:38.005269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72dac8c3b4bd'
down_revision = 'e2ac40f266b2'
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_search_vector', table_name='items')
    op.drop_column('items', 'search_vector')
    # ### end Alembic commands ###
