"""empty message

Revision ID: 89b2cc76a6ac
Revises: a80dee46e1a1
Create Date: 2020-09-19 17:17:47.644316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b2cc76a6ac'
down_revision = 'a80dee46e1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('looks', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'looks', 'lists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'looks', type_='foreignkey')
    op.drop_column('looks', 'list_id')
    op.drop_table('lists')
    # ### end Alembic commands ###
