"""empty message

Revision ID: 8d04827a5a25
Revises: 53609d2595a8
Create Date: 2020-07-11 10:40:33.618527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8d04827a5a25"
down_revision = "53609d2595a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('item_metadata', 'field_edited')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item_metadata", sa.Column("field_edited", sa.VARCHAR(), nullable=True)
    )
    # ### end Alembic commands ###
