"""empty message

Revision ID: 91ece0892a67
Revises: fbca933dcad3
Create Date: 2020-09-19 17:44:15.244355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ece0892a67'
down_revision = 'fbca933dcad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'lists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'list_id')
    # ### end Alembic commands ###
