"""empty message

Revision ID: 980893b75ee8
Revises: 
Create Date: 2020-05-03 14:38:28.550240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "980893b75ee8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('item_metadata', 'field_edited')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item_metadata", sa.Column("field_edited", sa.VARCHAR(), nullable=True)
    )
    # ### end Alembic commands ###
