"""empty message

Revision ID: bcfae80cc16f
Revises: 8d04827a5a25
Create Date: 2020-07-11 10:53:28.409040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bcfae80cc16f"
down_revision = "8d04827a5a25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('item_metadata', 'field_edited')
    op.add_column("items", sa.Column("deleted", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "deleted")
    op.add_column(
        "item_metadata", sa.Column("field_edited", sa.VARCHAR(), nullable=True)
    )
    # ### end Alembic commands ###
