"""empty message

Revision ID: ceb2bb227dce
Revises: 91ece0892a67
Create Date: 2020-09-30 22:39:21.680037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb2bb227dce'
down_revision = '91ece0892a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('items', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'updated_on')
    op.drop_column('items', 'created_on')
    # ### end Alembic commands ###
