"""empty message

Revision ID: e2ac40f266b2
Revises: 57669da10b7b
Create Date: 2020-08-09 00:43:13.685110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ac40f266b2'
down_revision = '57669da10b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('looks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('form_date', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_registrations',
    sa.Column('look_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['look_id'], ['looks.id'], )
    )
    op.add_column('comments', sa.Column('look_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'looks', ['look_id'], ['id'])
    op.add_column('thumbnails', sa.Column('look_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'thumbnails', 'looks', ['look_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thumbnails', type_='foreignkey')
    op.drop_column('thumbnails', 'look_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'look_id')
    op.drop_table('item_registrations')
    op.drop_table('looks')
    # ### end Alembic commands ###
