"""empty message

Revision ID: fbca933dcad3
Revises: 89b2cc76a6ac
Create Date: 2020-09-19 17:19:14.558198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbca933dcad3'
down_revision = '89b2cc76a6ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lists', 'about')
    # ### end Alembic commands ###
